### ISSUE TITLE
Allow filter preset to show hidden tasks

### ISSUE THREAD

**Issue by bnoellert** [mjdescy/TodoTxtMac#107]
Perhaps I'm doing something incorrect, but I would like to be able to set up a filter to be able to see the tasks that are currently "hidden" via the hide or threshold tags.  I tried the filter "hidden is **yes**" however nothing shows up.  If I uncheck the box in the Preferences to hide the tasks then they do re-appear.  Not quite sure if this is a bug or an enhancement request.  Thanks.

**Comment by mjdescy** [comment]
Right now, the “hide hidden tasks” preference asks as a super-filter that is applied no matter what you set in the filter preferences. The only way to view hidden tasks is to uncheck that box in preference. I didn’t make the “hidden is yes” filter that you can apply in the filter preferences override this behavior because I think it would make the “hide hidden tasks” behavior more fragile. So…it’s super consistent. You just have to uncheck that preference before you look for, and edit, your hidden tasks.

**Comment by bnoellert** [comment]
Makes sense.  I was able to get the behavior I wanted by removing the super-filter and just applying regular filters to the threshold dates.  Thanks!

**Comment by excetara2** [comment]
I was wanting something similar to this, so did you just make a filter so that your threshold dates beyond today are filtered out and then in the settings hide future tasks is unchecked instead of checked?

If I have hide future tasks checked, I can't find anyway to view the current thresholded items without unchecking that checkbox. Changing the filters doesn't help.
