### ISSUE TITLE
Bugs on rec:+1m ?

### ISSUE THREAD

**Issue by dbadolato** [mjdescy/TodoTxtMac#113]
Michael,

Congratulations for this nice and efficient app!

I've just switched to TodoTxtMac (v 2.3.0 2025) to use it as secondary way of managing my todo.txt (the file being sync on Dropbox and usually managed from the excellent SimpleTask on my Android).

I think there might be a bug on the rec: option. Or maybe it does not work exactly as in SimpleTask and I am doing something wrong...

When I complete this task:
(A) 2016-07-04 Pay NET @Internet t:2016-08-05 due:2016-08-10 rec:+1m

I get:
2016-08-08 -04 Pay NET @Internet t:2016-09-05 due:2016-09-10 rec:+1m
x 2016-08-08 2016-07-04 Pay NET @Internet t:2016-08-05 due:2016-08-10 rec:+1m

The -04 on the newly created task seems to be a bug.
And also, I would expect this new task to have the same priority (A) as the original one.

Other minor remarks:
- I don't know if it is intended, but after completion of this task on a filtered list, the whole task list is shown again, even if the filter applied before is still visible in the search window.
- It would be good to keep the priority in the completed task (why loose information which in some cases could be useful when analyzing the done.txt file?). In the example above, it would give (cf. the priority between the two dates):
x 2016-08-08 (A) 2016-07-04 Pay NET @Internet t:2016-08-05 due:2016-08-10 rec:+1m

Regards,
David

**Comment by mjdescy** [comment]
@dbadolato Thanks for the bug reports. 

## The rec:+1m bug

I will issue a fix for this bug. It only arises when "append creation date to new tasks" is enabled. That's not an option I use, which is why (obviously) I didn't write enough test cases to cover this feature.

## List filter dropped upon task completion

I am not seeing this behavior. If you hadn't told me the build number, I would have assumed you were using an older version of the app. There was a bug like this in the past.

There does seem to be some kind of bad filter behavior related to undo/redo that I haven't seen before. I will look into that. Maybe it is connected to this issue.

## Keeping priority on completed tasks

The reason priority is dropped from completed tasks is that's how the todo.txt command line tool works (at least at the time this app was created). I think there may be an add-on that keeps the priority, but I haven't implemented that. I will rethink that because you're not the first to inquire about that option.

**Comment by mjdescy** [comment]
Version 2.3.1 will close this issue.

**Comment by dbadolato** [comment]
Michael,
That was fast!
Thank you very much!
