### ISSUE TITLE
Edit state doesn't display properly

### ISSUE THREAD

**Issue by rdebeasi** [mjdescy/TodoTxtMac#118]
The display of the edit state was kind of glitchy for me on macOS 10.11, and it's gotten worse on macOS 10.12. The new text often overlaps the old text, and at times the text is not readable at all. I've attached screenshots.

I'm on a 2015 MacBook Pro with Intel Iris Pro graphics.

Otherwise, TodoTxtMac rocks - thanks for making it! 😄 
![screen shot 2016-11-21 at 10 15 13 am](https://cloud.githubusercontent.com/assets/1299370/20488077/bf518472-afd3-11e6-9b1e-5a7c93bad69e.png)
![screen shot 2016-11-21 at 10 15 35 am](https://cloud.githubusercontent.com/assets/1299370/20488078/bf532944-afd3-11e6-93be-626eb6ef71d5.png)

**Comment by mjdescy** [comment]
Hi, @rdebeasi. This bug arose due to the Sierra update. Every new version of macOS brings some subtle changes to Cocoa. I fixed this in the [App Store version of this app, called SwiftoDo Desktop](https://itunes.apple.com/us/app/swiftodo-desktop-task-list/id1143641091?ls=1&mt=12). I haven't ported the code back to TodoTxtMac yet because the code bases had to diverge a bit for the Mac App Store-specific stuff. I will get to that back porting eventually, but right now I'm working on the iOS app a ton.

**Comment by dwt** [comment]
@mjdescy If you could give some guidance where to start, I could take a look at a pull request. Haven't touched Cocoa Code in quite some years though.

**Comment by mjdescy** [comment]
I will issue a fix to TodoTxtMac today or tomorrow. Sorry I let this slide. Again, it was fixed in the App Store version but I didn't backport the change to this project.

**Comment by dwt** [comment]
Thanks!
