### ISSUE TITLE
ENH - allow todo task to be moved to other files

### ISSUE THREAD

**Issue by lalthomas** [mjdescy/TodoTxtMac#67]
David Allen GTD book describes the way of weekly review and making the inbox list to zero items. Well in order to accomplish similar thing in **todo.txt** system, there should be more than just a **done.txt**. I use a **later.txt** for moving the todos from **todo.txt** for the tasks which I find not relevant for this week. Can this app have a similar functionality like move to file on **Task** menu item, where it should display a recent list of files to where the tasks have been moved.

**Comment by mjdescy** [comment]
@lalthomas,

I may be able to do this in a future release. Such a feature isn't really one of my design goals, however, because the canonical todo.txt system only concerns itself with two main files, todo.txt and done.txt.

I could look into implementing cut-and-paste between task list windows, too, which may help you out somewhat with your use case.

**Comment by lalthomas** [comment]
@mjdescy thank you for the cut and paste [version 1.5.1]. It is really useful.

**Comment by mjdescy** [comment]
@lalthomas You're welcome. I originally left the cut command out because I didn't see the use case and it seemed risky, but since you have a clear use case, I added it. Everyone's a little happier now. :-)

**Comment by lalthomas** [comment]
I'm very happy :)
