### ISSUE TITLE
ENH - undo and redo functionality

### ISSUE THREAD

**Issue by lalthomas** [mjdescy/TodoTxtMac#74]
Well I know this is a big feature request, but it is a quite useful feature.

**Comment by mjdescy** [comment]
I would really like to add this feature, too. The Cocoa documentation for NSUndoManager is pretty hard to understand, however. It never was clear to me data structures I needed to provide to maintain the undo stack. 

There is a "Revert To" command in the File menu that offers a limited kind of undo functionality. That's built into Cocoa's NSDocument model.

I will research NSUndoManager again and see if I can figure it out.

**Comment by mjdescy** [comment]
I am actively working on implementing undo/redo for the next version. Undoing and redoing all commands that affect the task list itself will be included. I have not decided how to handle undo/redo for archiving tasks, however, and am soliciting input (see below).

The archive file is not kept open while using TodoTxtMac; it is only appended to when the user executes the archive command. Therefore, its state is not tracked in a way that can be used by the undo/redo stack. While I could capture the archive file's state each time the archive command is called for use in the undo/redo queue, that could take a lot of RAM over time, and may not lead to desirable behavior when undoing/redoing the edits to to the archive file. The archive file can be edited outside TodoTxtMac, so TodoTxtMac really has no reason to assume that it always knows what the proper state of that file should be.

I'm soliciting input on three options for undo/redo for the archive file:

1. One option, which I took off the table immediately, would be to not allow undos to the archive command. If you use the auto-archive completed tasks option, you will be archiving a lot and automatically deleting completed tasks from the task list. I don't want to provide no way to undo the deletion part of archiving of tasks, because toggling the completion state of tasks is probably the most common correction I make to my todo.txt file (I don't auto-archive completed tasks). 

2. Another option I have thought of is to simply not undo the edits to the archive file. TodoTxtMac could still undo the task deletion part of the archive command. Over time, there will be duplicate records appended to the archive file. 

3. Another option is to go ahead and make the best effort to undo the changes to the archive file. It is a little scary to be deleting tasks from the bottom of an archive file, but it should work without problems 95% of the time. This is much harder than the second option and may lead to data loss if unexpected things, such as additions, deletions, or re-sorting, happen to the archive file outside TodoTxtMac. I am OK with the risks on my end because I almost never edit my archive file directly, but it does not really conform to my goals for "no data loss" in the application.

**Comment by mjdescy** [comment]
Undo/redo will be added to the next version. There will be an option to limit the number of undos in the stack, in case you are concerned about RAM use. There will also be an option to disallow undo of the archive command, in case you are concerned about TodoTxtMac removing items from your archive file.

**Comment by lalthomas** [comment]
@mjdescy thank you so much...
