### ISSUE TITLE
Support recurring items

### ISSUE THREAD

**Issue by rtvb** [mjdescy/TodoTxtMac#77]
See https://github.com/bram85/topydo/wiki/Recurrence

**Comment by mjdescy** [comment]
Thanks for the suggestion, @robertvanbregt. 

Recurring tasks are an interesting feature that I have considered in the past. I'm not sure I want to add it to TodoTxtMac, however, for two reasons:

1. I think that recurring tasks are not a core feature of todo.txt. Unlike due dates and threshold dates, which are non-core features I do support, recurring tasks don't seem to have a lot of users or a single, dominant implementation. For example, [the link to topydo that you sent](https://github.com/bram85/topydo/wiki/Recurrence) shows a different way of handling recurring tasks than [a different todo.txt add-on](https://github.com/paulroub/todo.txt-recurring-tasks).

2. Adding recurring tasks *well* may be really difficult. The topydo implementation is simple and clever, but isn't really how I envisioned implementing recurring tasks in TodoTxtMac. I was thinking of something more akin to what a cron job would accomplish. (And why wouldn't a cron job do it better?)

I won't rule it out forever, but for now I don't foresee adding this feature. If users are clamoring for this feature, they can add comments to this thread to get my attention.

**Comment by robertvanbregt** [comment]
I am using https://github.com/bram85/topydo/ but also https://github.com/mpcjanssen/simpletask-android and both use the `rec:` syntax. I actually works pretty wel. Hope you reconsider.

**Comment by orionp** [comment]
Now that you have SwiftoDo out (very slick!), have you given any more thought to a possible solution that wouldn't require a cron job running? It would be excellent if this were possible from a mobile-only setup, in case it's a weekend where the laptop is packed, and the cron job doesn't get run. And since you have an app on two platforms now... #grin

Thank you for the amazing apps, regardless... very cool stuff!

**Comment by mruwek** [comment]
@mjdescy 
> And why wouldn't a cron job do it better?

1. Because cron-job depends on user's PC computer being powered on.
2. Users sometimes completes their tasks rather from mobile devices (like from simpletask mentioned above) than from PC.
3. Implementing cron-job script to check if a task was completed and then recreate it with proper `due:` tag seems like a overkill.
4. Two todo.txt apps with quite a userbase (topydo: 93 stars, simpletask: 107 stars) have implemented `rec:` syntax. Another two (SwiftoDo and TodoTxtMac) would help to provide "single, dominant implementation" across whole todo.txt world :)
5. Some users don't have access to create cron-jobs.

**Comment by rtvbnl** [comment]
@orionp Have a link to Swiftodo?

**Comment by orionp** [comment]
Indeed! [SwiftoDo](http://swiftodoapp.com)

**Comment by rtvbnl** [comment]
Hadn't noticed that. An app from @mjdescy . That could explain that there have been so little activity on this repo. :)

**Comment by mjdescy** [comment]
Yes, I've been very busy creating Swiftodo for iOS. The Todo.txt Touch app stopped working a while ago, and I decided to do a full rewrite because I wanted an iOS app.

I use TodoTxtMac to help me plan my work on SwitoDo. I feel like what I want to do is get a few more releases of SwiftoDo out to add the features I really want, then turn my attention back to the Mac platform later this year. I probably would release a "SwiftoDo Desktop" app in the App Store at some point, with a modest fee to help cover the annual Apple developer license fee. I do plan to keep TodoTxtMac working on new OS X releases, too.

**Comment by rtvbnl** [comment]
This is becoming a little off-topic. But if I contribute to the open sourced TodoTxtMac, I would not like my code to become part of your SwifttoDo Desktop, unless that would also be open sourced. I don't mind a little fee as you suggested, just like the original Todotxt Touch is not free.

**Comment by mjdescy** [comment]
I wouldn't mix code. I would write a brand new app in Swift using newer Cocoa frameworks. The core logic would be ported over from the iOS app pretty much unchanged. The UI is the major piece that would need a rewrite.

**Comment by mjdescy** [comment]
@rtvb I'm curious about this recurring tasks feature. _When_ are the tasks added in the other apps? Is it _only_ after you complete a task with a properly-formed "rec:" tag?

I am leaning toward implementing this, and I want to come up with the method that is (a) simple, and (b) could be implemented (by me) in SwiftoDo, TodoTxtMac, and possibly even Todotxt.net (provided Ben wants to allow it).

**Comment by rtvb** [comment]
I have not seen the code for the Android app, but topydo adds new tasks on completion of a specific task. So yes, *only* after/during completion. And the due and treshold dates vary depending on the rec: parmeters.

My current coding skills are limited, so it would take me quite some
time to code, but I could write specifications and/or pseudo code if you
like. If you promise to add the functionality to TodoTxtMac, you can use
that for SwiftoDo, too. :)

-- Robert

**Comment by mruwek** [comment]
@mjdescy 
> Is it only after you complete a task with a properly-formed "rec:" tag?

Yep. Executing `topydo.commands.DoCommand.execute()` calls [`topydo.commands.DoCommand._handle_recurrence()`.](https://github.com/bram85/topydo/blob/master/topydo/commands/DoCommand.py#L59)

Recurrence itself is handled by [topydo.lib.Recurrence](https://github.com/bram85/topydo/blob/master/topydo/lib/Recurrence.py) and [topydo.lib.RelativeDate](https://github.com/bram85/topydo/blob/master/topydo/lib/RelativeDate.py)

Hope this helps a bit :)

**Comment by mjdescy** [comment]
Support for recurring tasks is going to be the next major feature. I already coded it for [SwiftoDo](http://swiftodoapp.com) (that update, version 1.4.0, is pending (1) further testing and (2) my port of the feature to TodoTxtMac).

**Comment by orionp** [comment]
Incredible news! If you need TestFlight volunteers, please let us know!

Looking forward to it...

**Comment by rtvb** [comment]
Awesome! I didn't find the time to complete a PR yet so this will be very useful.

**Comment by mjdescy** [comment]
Commit 162c6a9a10692e6012f6b193121727c52121f5da introduces this behavior. It will be published in the next release.
