### ISSUE TITLE
Date calculates when editing and appending

### ISSUE THREAD

**Issue by rcraggs** [mjdescy/TodoTxtMac#80]
The automatic conversion of dates is very useful (e.g. Tomorrow -> 11-Jun-2015). This currently only happens when adding a new task. It would be very useful it this happened when editing a task or appending to a task.

**Comment by mjdescy** [comment]
This behavior is intentional. I do not want the app to try to modify tasks in *unexpected* ways (editing a non-due date part of the task shoudn't necessarily modify the due date). I did make an exception for transforming due dates during new task entry because that's what [Todotxt.net](https://github.com/benrhughes/todotxt.net) does. TodoTxtMac offers a lot of other functionality for modifying due dates for existing tasks, which I ended up porting over to Todotxt.net eventually, too. Maybe I could add a "always transform due dates and threshold dates" option to TodoTxtMac.
