### ISSUE TITLE
Sort does not work

### ISSUE THREAD

**Issue by rtvbnl** [mjdescy/TodoTxtMac#81]
Sort does not work on release 1.5.1 and 1.6.0. 
I am using Mac OS X 10.8.5.

I have tried all sort options, but none work, not even the Created date.
I can see changes in the view when selecting a different sort order, but none is doing it's work properly.

**Comment by mjdescy** [comment]
@robertvanbregt I am sorry to hear you are having problems. Sort works just fine for me. I'm running OX X 10.10 rather than 10.8 however. I don't think that should matter, but I don't have a way to test in your environment. The sorting code was written on OS X 10.9 and should be fully compatible with OS X 10.8.5; it hasn't changed much since inception, and I don't think anybody else opened issues related to it. I'm wondering if you could be suffering from a botched upgrade or something. I added additional user preferences in TodoTxtMac 1.5.0 (not 1.5.1) and 1.6.0. Because sort choice is kept in a user preference, it could have gotten screwed up by an upgrade that changed the default set of user preferences. That is kind of far fetched though. I don't know if there is anything I can do to fix this problem for you, rather than to suggest you uninstall TodoTxtMac with something like AppCleaner (to delete the user preferences) and try reinstalling.

**Comment by rtvbnl** [comment]
I'm currently using 10.11.x so I guess the issue can possible be closed.
