### ISSUE TITLE
Autocompletion should not close as user types suitable characters

### ISSUE THREAD

**Issue by singalen** [mjdescy/TodoTxtMac#86]
I have a context `@CallThem`. 
* Autocompletion opens when I type `@`, but closes as soon as I type `@C`. The dropdown should not close as long as I type suitable characters.
* Autocompletion should narrow down the completion list as the user types, e.g. exclude `@Office` context as I type `@C`.

**Comment by mjdescy** [comment]
I will look into this again. Autocompletion is tricky for this application because OS X does not want to treat "+" as a starting character, and likes to terminate its autocompletion instead of start it with that character and with "@". You kind of have to fight the native implementation a bit, which I did, or go super low-level and write your own implementation (which is beyond what I could support as OS X rolls forward).
