### ISSUE TITLE
Branch develop seriously behind master

### ISSUE THREAD

**Issue by rtvb** [mjdescy/TodoTxtMac#88]
Since you ask pull requests to be done to develop, thats branch should be in sync with master as much as possible. It currently is 30 commits behind.

**Comment by mjdescy** [comment]
I use the git flow branching model, and I have a gh-pages branch that contains content for the website. Since establishing that gh-pages branch, GitHub started reporting that develop is behind master. I don't really know why, or if gh-pages is even related. On my local repo, origin/head and origin/develop were both created by `git flow finish release '1.6.1'` and show the same commit message. 

Something probably got screwed up with git flow and I never tracked down what the issue is. Sorry about that. If you do want to contribute patches, let me know and we'll try to sort things out.
